version: '3.3'
services:
  app:
    build:
      context: .
    env_file: .env
    links:
      - amqp
    ports:
      - 8080:8080
  amqp:
    image: rabbitmq:3.7-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
